[package]
name = "heart_wrap"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
env_logger = "0.11.6"
libc = "0.2.169"
log = "0.4.25"
procfs = "0.17.0"
serde = "1.0.217"
serde_derive = "1.0.217"
serde_yaml = "0.9.34"
signal-hook = "0.3.17"
